CREATE TABLE announcements
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title      VARCHAR(255)                            NOT NULL,
    content    TEXT                                    NOT NULL,
    course_id  BIGINT                                  NOT NULL,
    posted_by  BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_announcements PRIMARY KEY (id)
);

CREATE TABLE assignments
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title         VARCHAR(255)                            NOT NULL,
    description   TEXT                                    NOT NULL,
    deadline      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    course_id     BIGINT                                  NOT NULL,
    instructor_id BIGINT                                  NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_assignments PRIMARY KEY (id)
);

CREATE TABLE course_enrollments
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course_id   BIGINT                                  NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    status      VARCHAR(255)                            NOT NULL,
    enrolled_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_course_enrollments PRIMARY KEY (id)
);

CREATE TABLE course_materials
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name    VARCHAR(255)                            NOT NULL,
    file_path    VARCHAR(255)                            NOT NULL,
    course_id    BIGINT                                  NOT NULL,
    content_type VARCHAR(255)                            NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_course_materials PRIMARY KEY (id)
);

CREATE TABLE courses
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title         VARCHAR(255)                            NOT NULL,
    description   TEXT                                    NOT NULL,
    max_capacity  INTEGER,
    is_active     BOOLEAN                                 NOT NULL,
    instructor_id BIGINT                                  NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_courses PRIMARY KEY (id)
);

CREATE TABLE grades
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    score         DOUBLE PRECISION                        NOT NULL,
    feedback      TEXT                                    NOT NULL,
    submission_id BIGINT                                  NOT NULL,
    student_id    BIGINT                                  NOT NULL,
    graded_by     BIGINT                                  NOT NULL,
    graded_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_grades PRIMARY KEY (id)
);

CREATE TABLE live_sessions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title         VARCHAR(255)                            NOT NULL,
    scheduled_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    started_at    TIMESTAMP WITHOUT TIME ZONE,
    ended_at      TIMESTAMP WITHOUT TIME ZONE,
    is_active     BOOLEAN                                 NOT NULL,
    course_id     BIGINT                                  NOT NULL,
    instructor_id BIGINT                                  NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_live_sessions PRIMARY KEY (id)
);

CREATE TABLE refresh_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token      VARCHAR(255)                            NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_revoked BOOLEAN                                 NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

CREATE TABLE session_questions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    question_text TEXT                                    NOT NULL,
    is_answered   BOOLEAN                                 NOT NULL,
    answered_at   TIMESTAMP WITHOUT TIME ZONE,
    session_id    BIGINT                                  NOT NULL,
    asked_by      BIGINT                                  NOT NULL,
    asked_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_session_questions PRIMARY KEY (id)
);

CREATE TABLE submission_files
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name     VARCHAR(255)                            NOT NULL,
    file_path     VARCHAR(255)                            NOT NULL,
    content_type  VARCHAR(255),
    file_size     BIGINT,
    submission_id BIGINT                                  NOT NULL,
    uploaded_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_submission_files PRIMARY KEY (id)
);

CREATE TABLE submissions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    assignment_id BIGINT                                  NOT NULL,
    student_id    BIGINT                                  NOT NULL,
    notes         TEXT,
    status        VARCHAR(255)                            NOT NULL,
    submitted_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_submissions PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    user_name  VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    role       VARCHAR(255)                            NOT NULL,
    is_active  BOOLEAN                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE grades
    ADD CONSTRAINT uc_grades_submission UNIQUE (submission_id);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_token UNIQUE (token);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_user_name UNIQUE (user_name);

ALTER TABLE announcements
    ADD CONSTRAINT FK_ANNOUNCEMENTS_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE announcements
    ADD CONSTRAINT FK_ANNOUNCEMENTS_ON_POSTED_BY FOREIGN KEY (posted_by) REFERENCES users (id);

ALTER TABLE assignments
    ADD CONSTRAINT FK_ASSIGNMENTS_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE assignments
    ADD CONSTRAINT FK_ASSIGNMENTS_ON_INSTRUCTOR FOREIGN KEY (instructor_id) REFERENCES users (id);

ALTER TABLE courses
    ADD CONSTRAINT FK_COURSES_ON_INSTRUCTOR FOREIGN KEY (instructor_id) REFERENCES users (id);

ALTER TABLE course_enrollments
    ADD CONSTRAINT FK_COURSE_ENROLLMENTS_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE course_enrollments
    ADD CONSTRAINT FK_COURSE_ENROLLMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE course_materials
    ADD CONSTRAINT FK_COURSE_MATERIALS_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE grades
    ADD CONSTRAINT FK_GRADES_ON_GRADED_BY FOREIGN KEY (graded_by) REFERENCES users (id);

ALTER TABLE grades
    ADD CONSTRAINT FK_GRADES_ON_STUDENT FOREIGN KEY (student_id) REFERENCES users (id);

ALTER TABLE grades
    ADD CONSTRAINT FK_GRADES_ON_SUBMISSION FOREIGN KEY (submission_id) REFERENCES submissions (id);

ALTER TABLE live_sessions
    ADD CONSTRAINT FK_LIVE_SESSIONS_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE live_sessions
    ADD CONSTRAINT FK_LIVE_SESSIONS_ON_INSTRUCTOR FOREIGN KEY (instructor_id) REFERENCES users (id);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT FK_REFRESH_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE session_questions
    ADD CONSTRAINT FK_SESSION_QUESTIONS_ON_ASKED_BY FOREIGN KEY (asked_by) REFERENCES users (id);

ALTER TABLE session_questions
    ADD CONSTRAINT FK_SESSION_QUESTIONS_ON_SESSION FOREIGN KEY (session_id) REFERENCES live_sessions (id);

ALTER TABLE submissions
    ADD CONSTRAINT FK_SUBMISSIONS_ON_ASSIGNMENT FOREIGN KEY (assignment_id) REFERENCES assignments (id);

ALTER TABLE submissions
    ADD CONSTRAINT FK_SUBMISSIONS_ON_STUDENT FOREIGN KEY (student_id) REFERENCES users (id);

ALTER TABLE submission_files
    ADD CONSTRAINT FK_SUBMISSION_FILES_ON_SUBMISSION FOREIGN KEY (submission_id) REFERENCES submissions (id);



INSERT INTO users (
    first_name,
    last_name,
    user_name,
    email,
    password,
    role,
    is_active,
    created_at,
    updated_at
) VALUES (
             'Super',
             'Admin',
             'superadmin',
             'admin@example.com',
             '$2a$12$7MAWbBTPxeGtPj6Jg5wb1e2beHxSYlO9QhUY61Fz3Qc1jTQH3WxV6',
             'SUPER_ADMIN',
             true,
             CURRENT_TIMESTAMP,
             CURRENT_TIMESTAMP
         );
